version: "3.9"

services:
  short-creator:
    build:
      context: .
      dockerfile: main.Dockerfile # set environment variable DOCKERFILE
    env_file:
      - .env
    environment:
      - DEV=true
      - DOCKER=true
      - DATA_DIR_PATH=/app/data
    ports:
      - "3123:3123"
    command: pnpm run start
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
    restart: unless-stopped
